### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by PingForward** [antoniolg/androidmvp#13]
Could you add a simple unit testing of this architecture?

**Comment by sadegh** [comment]
👍

**Comment by yudehai0204** [comment]
Yeah!  I also  see a simple test;

**Comment by sukantamaikap** [comment]
Ye, would love to have that too ..

**Comment by antoniolg** [comment]
Feel free to create a PR and I'll be glad to review it. Don't think I have time soon to do this.

**Comment by ruanjiankeji** [comment]
A simple test

**Comment by antoniolg** [comment]
Closed by https://github.com/antoniolg/androidmvp/pull/17
