### ISSUE TITLE
how make request for one api

### ISSUE THREAD

**Issue by enieber** [antoniolg/androidmvp#19]
I like this project, but i am confused about how to organize my requests for one api and how to organize my access for database.

**Comment by antoniolg** [comment]
Well, that's part of the rest of the architecture, so it depends on how you want to organize it. You can check this repository to have an idea of a clean architecture: https://github.com/PaNaVTEC/Clean-Contacts

**Comment by enieber** [comment]
Thanks....

**Comment by enieber** [comment]
how make request for one api

**Comment by enieber** [comment]
Thanks..
