### ISSUE TITLE
[Question] Which is better using contact? or dividing presenter between view interface?

### ISSUE THREAD

**Issue by binsolb** [antoniolg/androidmvp#31]

**Comment by antoniolg** [comment]
Sorry, don't understand de question 😕

**Comment by piotrek1543** [comment]
@antoniolg he' asking which approach is better:
- defining one `Contract` interface per package which would have internal interfaces for `View`, `Presenter`, `Model` etc. which is used especially in `googles-samples` like here:
https://github.com/googlesamples/android-architecture/blob/todo-mvp-clean/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksContract.java
or
- defining seperate interface for every purpose like `View`, `Presenter`, `Repository`.

@binsolb it doesn't matter, both approaches are more cosmetic than functional. Choose your favorite.

**Comment by antoniolg** [comment]
Closing this issue then! Thanks for your help @piotrek1543
